guardian/content-api-models

- build.sbt
- project/plugins.sbt
- version.sbt
The world is not quite ready for Bintray. Let's go back to the tried and tested Maven Central via Sonatype method for publishing.
See https://github.com/sbt/sbt/issues/2464 for more details. Basically JCenter had some reliability problems, so it's disabled by default in sbt for now. Telling our users to enable it is quite a big ask.
> Back to good ol' Sonatype

- src/main/thrift/content/v1.thrift
Initially this is to support most-viewed videos data. In future we may add more info to this response.
> Add VideoStatsResponse to CAPI thrift model

- json/src/main/scala/com.gu.contentapi.json/JsonParser.scala
- json/src/test/resources/templates/packages.json
- json/src/test/scala/com/gu/contentapi/json/JsonParserPackagesTest.scala
This is currently required by Concierge, and may at some point be needed by content-api-scala-client
> Add packages to json parser

- build.sbt
* Move the dependencies to the `json` project where they belong
* Scrooge should be 4.5.0 to match what we use in other projects
* Downgrade libthrift to 0.9.1 to fix the incompatible equals() change
The reason for downgrading libthrift is that Scrooge is compiled against libthrift 0.5.0-1 (Twitter's fork), which turns out to be incompatible with 0.9.2 or newer. 
When it deserializes a struct containing one or more optional fields that it doesn't understand, its `equals` method delegates to the one provided by `libthrift`. But the signature of that method changed between 0.9.1 and 0.9.2. [Here](https://github.com/apache/thrift/commit/97243a73eab86b634540756f72be1c500cfeea6c#diff-decddb5b3bdeea999d3c19fa200d3bfcR56) is the change that cost us a whole day of debugging, nestled away inside …
> Sort out the Scrooge/libthrift dependencies

- json/src/main/scala/com/gu/contentapi/json/JsonParser.scala
- json/src/main/scala/com/gu/contentapi/json/Serialization.scala
- json/src/test/resources/templates/atom-usage.json
- json/src/test/resources/templates/item-content.json
- json/src/test/scala/com/gu/contentapi/json/JsonParserItemTest.scala
- json/src/test/scala/com/gu/contentapi/json/JsonParserSearchTest.scala
- json/src/test/scala/com/gu/contentapi/json/SerializationSpec.scala
- json/src/test/scala/com/gu/contentapi/json/utils/CapiModelEnrichment.scala
- models/src/main/thrift/content/v1.thrift
* Add helper methods to stringify parts of the JSON
* Customise the String repr of `Office` enum: unlike other enums, this one is uppercase
* Fix the `thriftEnum2JString` method
* Add a test for round-tripping an ItemResponse containing a piece of content
* Extend the `CapiDateTime` struct to preserve timezone information
* Update/fix some test data
Still to do in later PRs:
* Crosswords (nearly works, just need to tweak the date formats)
* Atoms (haven't looked at it yet, but it will probably be a nightmare)
* Tests for other kinds of ItemResponse (section, tag) and more complex variations of Content
> Big step towards working JSON serialization of Content struct

- models/src/main/thrift/content/v1.thrift
Adds the new fields introduced in https://github.com/guardian/content-api/pull/1543 into the thrift model.
> Adds paidContentType and aboutLink commercial fields

- .gitignore
- build.sbt
- models/src/main/thrift/events/crier/event.thrift
Most clients have to rely on this project anyway when using Crier so it makes sense for the events.thrift file to live in here also. This also prevents it from being copied and posted everywhere.
> Move events.thrift from Crier into content-api-models.

- json/src/main/scala/com/gu/contentapi/json/Serialization.scala
- models/src/main/thrift/content/v1.thrift
This is needed by Crier and possibly other apps.
> Expose the internal revision number field

- models/src/main/thrift/events/crier/event.thrift
I should've merged this before releasing the new model, oops. Sorry.
> Add internal revision field to Crier's model

- models/src/main/thrift/content/v1.thrift
I had to move `struct Section` and `struct Edition` further up before `struct Content` because I'm now referencing `Section` from `Content`
> Add the Section field to Content

- build.sbt
- json/src/main/scala/com/gu/contentapi/json/JsonDeserializer.scala
- json/src/main/scala/com/gu/contentapi/json/JsonParser.scala
- json/src/main/scala/com/gu/contentapi/json/Serialization.scala
- json/src/main/scala/com/gu/contentapi/utils/CapiModelEnrichment.scala
- json/src/test/resources/templates/item-content-with-atom-quiz.json
- json/src/test/resources/templates/item-content-with-atom-viewpoints.json
- json/src/test/resources/templates/item-content-with-blocks.json
- json/src/test/resources/templates/item-content-with-crossword.json
- json/src/test/resources/templates/item-content-with-membership-element.json
- json/src/test/resources/templates/item-content-with-package.json
- json/src/test/resources/templates/item-content-with-rich-link-element.json
- json/src/test/resources/templates/item-content-with-tweets.json
- json/src/test/resources/templates/item-section.json
- json/src/test/resources/templates/item-tag.json
- json/src/test/resources/templates/packages.json
- json/src/test/resources/templates/search.json
- json/src/test/scala/com/gu/contentapi/json/JsonParserEditionsTest.scala
- json/src/test/scala/com/gu/contentapi/json/JsonParserItemTest.scala
- json/src/test/scala/com/gu/contentapi/json/JsonParserSearchTest.scala
- json/src/test/scala/com/gu/contentapi/json/JsonParserVideoStatsTest.scala
- json/src/test/scala/com/gu/contentapi/json/SerializationSpec.scala
- models/src/main/thrift/content/v1.thrift
This PR completes the 'thriftification' work on the capi models library. See [here](https://github.com/guardian/content-api/pull/1510) for background explanation.
- 'Round-trip' tests for all response types
- Moved the JsonDeserializer object from Concierge to here.
- Deserialize (json --> thrift) Atoms and Atom objects. We can now "round-trip" the json. This also involves a change to concierge to make the generated json match the structure of the thrift model.
- Viewpoints don't quite work, but I've commented out the failing tests because we don't care about them.
- Add missing fields to AssetFields thrift model, since this needs to be the superset of all element fields lists.
- Change `PackageResponse` to `PackagesResponse`
- Various other thrift model fixes...
> Complete thriftification

- build.sbt
This broke the concierge build, because content-api-models-json picked up the model class files
> Fix the build

- models/src/main/thrift/content/v1.thrift
For clients to use the new custom instagram element in CAPI.
[Initial defintion](https://github.com/guardian/content-api/pull/1589/files)
[Update to include alt and caption](https://github.com/guardian/content-api/pull/1596/files)
> adds instagram to thift

- models/src/main/thrift/content/v1.thrift
Comments was already a custom element but had no custom element field... until today! 
[Fields added to porter](https://github.com/guardian/content-api/pull/1553)
> adds comment fields

- json/src/test/scala/com/gu/contentapi/json/JsonParserItemTest.scala
- models/src/main/thrift/content/v1.thrift
This was a breaking change introduced in preparation for thriftification, but we've decided it's not worth the pain
> Make Rights fields required, default to false

- macros/src/main/scala/com/gu/contentapi/circe/CirceScroogeMacros.scala
Instead of using [slow regex pattern compilation](http://stackoverflow.com/questions/6262397/string-replaceall-is-considerably-slower-than-doing-the-job-yourself) each time we simply intend to remove all `-` char occurrences we use an implementation that iterates on the char sequence.
Using 
```
jmh:run -i 20 -wi 20 -f1 -t1 .*JsonDecodeBenchmark.*
```
Before:
```
[info] Benchmark                                        Mode  Cnt        Score        Error  Units
[info] JsonDecodeBenchmark.circe                        avgt   20   245473.327 ±  38121.982  ns/op
[info] JsonDecodeBenchmark.circeDeserializeEachContent  avgt   20  3594792.021 ± 504839.078  ns/op
```
After
```
[info] Benchmark                                        Mode  Cnt        Score       Error  Units
[info] …
```
> Improve deserialisation performance 

- build.sbt
The `scala` project is now a provided dependency meaning we no longer need this code.
> Remove mappings for json project.

- benchmarks/src/main/scala/benchmark/JsonDecodeBenchmark.scala
- build.sbt
- macros/src/main/scala/com/gu/contentapi/circe/CirceScroogeMacros.scala
This is because use of Lazy incurs a runtime cost. We should only use it when we need it to hack around implicit resolution problems in the compiler.
Before:
```
[info] Benchmark                                        Mode  Cnt        Score       Error  Units
[info] JsonDecodeBenchmark.circe                        avgt   40   104592.251 ±  4303.060  ns/op
[info] JsonDecodeBenchmark.circeDeserializeEachContent  avgt   40  1751011.694 ± 93215.817  ns/op
```
After:
```
[info] Benchmark                                        Mode  Cnt        Score       Error  Units
[info] JsonDecodeBenchmark.circe                        avgt   40    95609.173 ±  1740.968  ns/op
[info] JsonDecodeBenchmark.circeDeserializeEachContent  avgt   40  1344281.162 ± 47547.969  ns/op
```
Also
* Add a benchmark for a …
> Improve the Thrift struct Decoder macro to only use shapeless Lazy where necessary

- macros/src/main/scala/com/gu/contentapi/circe/CirceScroogeMacros.scala
We piggyback on the builtin Decoder for String to write the same thing in a slightly less verbose way.
> Simplify the macro-generated Decoder for ThriftEnum

- models/src/main/thrift/content/v1.thrift
for accessing individual cta atoms via the `atom/cta/<id>` endpoint
> add cta to item response

- models/src/main/thrift/content/v1.thrift
This change updates the thrift definition to support sponsorship logo dimensions.
It comes after 
1. https://github.com/guardian/content-api/pull/1711 , and 
2. https://github.com/guardian/content-api/pull/1714
The dimensions are published by the tag manager here: https://github.com/guardian/tags-thrift-schema/blob/master/src/main/thrift/image.thrift
> Update of the thrift definition to support sponsorship logo dimensions

- models/src/main/thrift/content/v1.thrift
This is for alexa (but possibly other apps later).
The `bodyText` does not contain any tags. The `charCount` is the number of chars in `bodyText`, and will allow us to exclude long articles.
> Add bodyText and charCount fields

- models/src/main/thrift/content/v1.thrift
We would like to keep track of the vidispineId so that we can track back from a video page that was created by pluto, to that entry in pluto.
This PR is the first step. There will also be changes to composer and porter to actuall fill this field in.
> add field for vidispineid

- models/src/main/thrift/content/v1.thrift
This adds more information about content atom elements at a block level.
Adding 2 fields for content atom elements:
- Atom ID
- Atom Type
Changes discussed with @clloyd and @mchv
> Add Content Atom Type and ID Data to atom elements

- build.sbt
- include legallySensitive flag for atoms (2.4.14)
- make currency value an int (2.4.15)
> Bump content-atom to 2.4.15

- build.sbt
https://github.com/guardian/content-atom/pull/60
> Bump content-atom to 2.4.16

- build.sbt
New content-atom-model version with [fixed type for `year` field](https://github.com/guardian/content-atom/pull/69)
I have not introduced cross-compiling for scala 2.12 because it is incompatible with the currently-used version of circe, and upgrading to circe 0.6 will require some code changes.
> Bump content-atom-model to 2.4.23

- build.sbt
To make review `genre` field a list - https://github.com/guardian/content-atom/pull/70
> Bump content-atom-model to 2.4.26

- json/src/main/scala/com/gu/contentapi/json/CirceDecoders.scala
- json/src/main/scala/com/gu/contentapi/json/CirceEncoders.scala
- macros/src/main/scala/com/gu/contentapi/circe/CirceScroogeMacros.scala
This library currently has a custom decoder and encoder for `Atom`, because `AtomData` is a thrift union type and our standard macros cannot handle unions. This is annoying because we have to update this code every time an atom is added to the model.
This change adds macros for generating decoders and encoders for scrooge's thrift union types, meaning fewer code changes in future.
> Thrift union macros

- build.sbt
See [atom related changes](https://github.com/guardian/content-atom/pull/75)
> Bumping the version of content-atom-model to 2.4.28

- models/src/main/thrift/content/v1.thrift
I think it will not break anyome
Current display is wrong:
```json
"debug": {
"lastSeenByPorterAt": "2017-01-10T12:01:58Z",
"revisionSeenByPorter": "0145-01-01T00:00:00Z",
"contentSource": "flexible"
},
```
> Fix the format of revisionSeenByPorter

- build.sbt
- Includes models for story questions atom.
> Bump content-atom dependency to 2.4.32.

- models/src/main/thrift/content/v1.thrift
`categories` - these will correspond to the [google knowledge graph entity types](https://developers.google.com/knowledge-graph/)
The [model in tag manager](https://github.com/guardian/tagmanager/blob/master/app/model/Tag.scala#L27) already has an (unused) `categories` field.
`entityIds` - these will be any associated [entities](https://github.com/guardian/content-entity/pull/6)
> Add categories field to Tag model

- models/src/main/thrift/content/v1.thrift
Adds fields optional field `shouldHideReaderRevenue`
See flexible changes [here](https://github.com/guardian/flexible-model/pull/3).
> adds reader revenue field

- build.sbt
https://github.com/guardian/content-atom/pull/92
> content-atom-model 2.4.41

- build.sbt
- json/src/main/scala/com/gu/contentapi/json/CirceDecoders.scala
This picks up 2 changes, neither of which content-api-models needs:
1. Supports [accumulated errors](https://github.com/guardian/fezziwig/pull/11)
2. Newer versions of circe and thrift/scrooge - https://github.com/guardian/fezziwig/pull/12/files
I've rearranged some of the implicit decoder definitions as this improves compilation times.
A concierge test fails without this new `dateTimeDecoder`.
This has led to the discovery that dateTime fields under `requestedBodyBlocks` are being incorrectly serialized to json as objects rather than strings. It's not clear why this is happening - I'll fix it separately.
It's also not clear why bumping the fezziwig version has broken decoding of this json back to thrift. It was somehow working before - even though the old `dateTimeDecoder` was telling it …
> Fezziwig 0.4

- models/src/main/thrift/content/v1.thrift
- Add "originatingSystem" field to the thrift model
This change is part of the process to add an "originatingSystem" field from flex to capi. This field will be used by the Tools team for metrics purposes.
Porter changes pr [here](https://github.com/guardian/content-api/pull/1987)
Flexible Model pr [here](https://github.com/guardian/flexible-model/pull/8)
Elastic Search pr [here](https://github.com/guardian/content-api/pull/1985)
> Add field to the thrift model

- build.sbt
- json/src/test/scala/com/gu/contentapi/json/CirceRoundTripSpec.scala
- project/plugins.sbt
Bumping the scrooge version is safe.
libthrift must not go beyond 0.9.1.
Circe 0.8.
Also switched from cornichon to diffson for json diffs in tests.
> Upgrade to scala 2.12.3

- build.sbt
Only `content-api-models-scala` should have the scala version appended!
> Disable crossPaths

- build.sbt
- version.sbt
An earlier change enabled cross publishing (2.11 and 2.12). This had the unwanted side-effect of adding the scala version to the end of the name for *all* projects published by this library:
- `content-api-models-scala_2.12` - wanted
- `content-api-models-json_2.12` - not wanted
- `content-api-models_2.12` - not wanted
This other change that I reverted here attempted to fix this, but sbt doesn't allow you to only set `crossScalaVersions` for one project in a multi-project build. So the result was that only 2.12 was published.
We've decided to accept having scala versions after all projects, as we need cross publishing.
> Revert cross paths change

- build.sbt
Changes in:
Porter https://github.com/guardian/content-api/pull/2021
Elasticsearch mapping https://github.com/guardian/content-api/pull/2020
> Bump to latest version of atom models to include new Timeline field

- json/src/main/scala/com/gu/contentapi/json/CirceDecoders.scala
- json/src/test/scala/com/gu/contentapi/json/CirceRoundTripSpec.scala
The recent move from joda to java time breaks the decoding of elasticsearch json in Concierge.
This is because some of these fields have only a date, and the joda time parser was less strict.
I've tested locally with concierge.
@annebyrne this was blocking your concierge version bump :(
> Make time optional in CapiDateTime decoder

- models/src/main/thrift/content/v1.thrift
In the iOS 11 update, we can now include podcast level information about the `type` of the podcast, whether they are serial or episodic. This will impact how episodes of podcast are shown to the user.
> Include podcast level info about types - serial or episodic

- json/src/main/scala/com/gu/contentapi/json/CirceDecoders.scala
- json/src/main/scala/com/gu/contentapi/json/CirceEncoders.scala
- models/src/main/thrift/content/v1.thrift
In addition to `sectionId`/`sectionName`, capi will now also return the pillar details.
Concierge will determine the pillar from the content's `sectionId`.
> Add pillar fields to Content

- build.sbt
To support the `scheduledLaunch` field in atoms - https://github.com/guardian/content-atom/pull/112
> content-atom 2.4.52

- build.sbt
Associated relevant PRs for change that have been merged:
> Bump version to include new Snippet Timeline date formats

- build.sbt
Added new properties to content atom models, so bumping the version here to pull in the latest 
[Trello Ticket](https://trello.com/c/GexFvYIf/240-add-new-fields-for-atom-images-adding-fields-for-atom-images-copyright-source-photographer-suppliersreference-so-rcs-can-better)
> Increment version of content-atom-models 

- .travis.yml
- build.sbt
In Ophan we use both the Content API client and [`play-googleauth`](https://github.com/guardian/play-googleauth).
`play-googleauth` was recently updated to use Cats 1.0.1 with https://github.com/guardian/play-googleauth/pull/49, and we have our own PR sitting on top of this (https://github.com/guardian/play-googleauth/pull/52) that we want to start using - but first we need the Content API client to also be updated to Cats 1.0, along with Circe etc, otherwise we get all kinds of _runtime_ errors, some of the associated with the Circe version, eg:
```
java.lang.NoSuchMethodError: io.circe.Decoder$.decodeCanBuildFrom(Lio/circe/Decoder;Lscala/collection/generic/CanBuildFrom;)Lio/circe/Decoder;
at com.gu.contentapi.json.CirceDecoders$.<init>(CirceDecoders.scala:82)
at …
```
> Upgrade to Cats 1.0 - by upgrading relevant libraries that use it

- models/src/main/thrift/content/v1.thrift
This field will be set in composer, and used by frontend to determine whether affiliate links are displayed within an article.
Background: We're going to start automatically adding affiliate links to content in certain sections (e.g. lifeandstyle). They come from a service called skimlinks. Sometimes we'll need to manually turn them off for sensitive content, or force them to be on for content not in one of the whitelisted sections.
> Add new showAffiliateLinks field

- models/src/main/thrift/content/v1.thrift
This creates a new tag type `campaign`
Related work:
Elastic Search - https://github.com/guardian/content-api/pull/2135
Porter - https://github.com/guardian/content-api/pull/2136
Tag Manager - guardian/tagmanager#317
> Tags: Add new tag type

- json/src/main/scala/com/gu/contentapi/json/CirceDecoders.scala
- json/src/main/scala/com/gu/contentapi/json/CirceEncoders.scala
- models/src/main/thrift/content/v1.thrift
Needed by crier for [new design](https://github.com/guardian/crier/pull/79).
For backwards-compatibility, this must be a new field.
It can be optionally returned by capi if clients request it
> Add lastModified to RemovedContentResponse

- json/src/main/scala/com/gu/contentapi/json/CirceDecoders.scala
- json/src/main/scala/com/gu/contentapi/json/CirceEncoders.scala
- json/src/test/resources/templates/item-content.json
Following the update of Porter, we now serialise timestamps with milliseconds precision when available for the `lastSeenByPorterAt` field. Sadly this requires a custom `Debug` encoder.
> Add support for fractional part in timestamps

- models/src/main/thrift/content/v1.thrift
We want Podcast series to have a `googlePodcastsUrl` link as well as an iTunes one (named `subscriptionUrl`.
Related: 
https://github.com/guardian/content-api/pull/2171
https://github.com/guardian/content-api/pull/2170
> Tag Podcast change: Add google podcasts url

- build.sbt
This update brings the version of content-atom that [enforces the version of libthrift to 0.9.1](https://github.com/guardian/content-atom/pull/128)
> Bump content-atom

- models/src/main/thrift/content/Platform.thrift
- models/src/main/thrift/content/v1.thrift
A few key changes:
- `platform` becomes a `publicationInstance`, i.e. a place where this content has been published
- in the main model this is now a list as something can be published in multiple locations
- we mimic the element structure with an enum to select the platform for a publication instance and then different structs for each type
- we include the pub/book/book-section 'tags' in print (these might become something other than tags if better)
> Some tweaks to build on modelling non-web content

- build.sbt
- json/src/main/scala/com/gu/contentapi/json/CirceDecoders.scala
- json/src/main/scala/com/gu/contentapi/json/CirceEncoders.scala
- models/src/main/thrift/content/v1.thrift
Stories have been deleted from the scala client (see https://github.com/guardian/content-api-scala-client/pull/289) and CAPI (see https://github.com/guardian/content-api/pull/2304) so the models can also be cleaned out - when any clients have been updated.
> Remove stories

- models/src/main/thrift/content/v1.thrift
Following the [work in tagmanager](https://github.com/guardian/tagmanager/pull/371), we can now publish that into CAPI.
> Add Acast ID for podcasts

- build.sbt
- models/src/main/thrift/content/v1.thrift
Now we have defined an emailsignup atom in https://github.com/guardian/content-atom/pull/133  and the latest version of [content-atom-model-thrift](https://search.maven.org/artifact/com.gu/content-atom-model-thrift) has been published, I'd like to use the latest version of content-atom-model-thrift
> Add hook for emailsignup atoms

- README.md
- build.sbt
- models/src/main/thrift/content/v1.thrift
- models/src/main/thrift/events/crier/event.thrift
- models/src/main/thrift/events/flexible/auxiliaryAtomEvent.thrift
- project/build.properties
- project/plugins.sbt
- Upgrade the release pipeline
- Add support for typescript
- Update the readme
~This PR currently doesn't compile as it relies on the [yet-to-be-released story packages version](https://github.com/guardian/story-packages-model/pull/13).~ => released!
> Support typescript

- build.sbt
Pull in the updated atom definitions that contain the placeholderUrl field.
See also: https://github.com/guardian/content-atom/pull/142 and https://github.com/guardian/content-api/pull/2520
> Bring in updated atom model (with placeholderUrl)

- README.md
- json/src/main/scala/com/gu/contentapi/json/CirceDecoders.scala
- json/src/main/scala/com/gu/contentapi/json/CirceEncoders.scala
- models/src/main/thrift/content/v1.thrift
- version.sbt
Adds an initial field to the embed element to document the tracking status of this 3rd party embed (if known).
This is a step towards the UI been able to ask the end user for informed concent before rending a potentially tracked embed.
Proposal: https://docs.google.com/document/d/1-6RWIHEUnjGHHvBCaXlhXy08RqAtmO_kJAnZXK5cv48
Content api model is a public artefact.
Publishing this field potentially signals to outside parties that we have a concern in this area which we have not yet addressed.
> Add a typed embed tracking status field to embed element.

- models/src/main/thrift/content/v1.thrift
Optional field which will render of the element is deemed to potentially contain tracking embeds
Optional tracking field shown appearing on an embed and text element.
Promotes the track field for general use on all applicable block elements.
This field has never used in it's initial position under the embed element. Promoting it is considered safe.
> Element tracking field is promoted from embed element to all block elements

- models/src/main/thrift/content/v1.thrift
Adds the 'role' field to Block Element types which did not already have it; notably embed and atom.
As per: https://trello.com/c/cuA5lpWH/1290-embed-role-not-modelled-in-capi-block-element-view
Adding a embed element in Composer should result in the role field appearing in the CAPI Block Element.
This is a field addition. It should be safe.
> Element role additions

- models/src/main/thrift/content/v1.thrift
- models/src/main/thrift/events/crier/event.thrift
The evolving URLs work has highlighted a need to make alias paths available in CAPI responses, in particular to service de-caching operations where an item of content may have been cached under any or all of its prior paths.
In this PR we are adding an `optional list<string> aliasPaths` to the `v1.content` representation, and to the `RetrievableUpdate` type in Crier. The former will allow Concierge to include the data in its responses, and the latter will allow Crier to pass that data on in its update messages.
The reason we need the data in both places is because the content is not guaranteed to be available in the message payload when the cache purger receives it (hence the existence of the _RetrievableUpdate_ type), but in this case we _don't_ want to introduce a lookup back to CAPI, …
> Add optional aliasPaths to Content + Crier's RetrievableUpdate

- models/src/main/thrift/events/fastly/event.thrift
Introduces an event to represent Fastly CDN decaches.
Includes some basic meta data which the consume may find useful.
Intended as a lightweight substitute of the crier Event which can be iterated on to better suit the decached content use case.
> New event to represent a successful content decache

- models/src/main/thrift/events/crier/event.thrift
Provides a new type of content update payload to document the the optional alias paths of a piece of deleted content.
A content deleted update may start to provided this payload; currently content deleted events have no payload set.
> Deleted Content payload

- models/src/main/thrift/content/v1.thrift
This change is part of the work to render a privacy 'overlay' for embedded content that requires the user to consent/click the overlay before the embed isloaded. 
To do this we need to have a correct size to render the overlay.
The height and width fields already exist in a lot of the element type data types, this change ensures all the element types that can contain embedded content have a height and width field.
This is an addition of an optional field so is low risk
> Adding height and width to elements that can contain embedded content

- models/src/main/thrift/content/v1.thrift
Adding sourceDomain to the 'ElementFields' for elements that have embedded content
This will identify where the embedded content comes from and will be
useful where a human readable 'source' is not available
> Adding sourceDomain to the '*ElementFields'

- models/src/main/thrift/content/v1.thrift
This reverts the changes to add height and width to various element types.
https://github.com/guardian/content-api-models/pull/191
This change turned out not to be useful so its being removed to avoid unused clutter.
> Reverting: Adding height and width to elements that can contain embedded content

- models/src/main/thrift/events/fastly/event.thrift
Rename content id to content path; as it is a path which Fastly has decached.
Retire the aliasPath field as content items which multiple paths will issue multiple decaches; consumers should react to each seperate decached path.
> Content decached message clean up.

- json/src/main/scala/com/gu/contentapi/json/CirceDecoders.scala
- json/src/main/scala/com/gu/contentapi/json/CirceEncoders.scala
- models/src/main/thrift/content/v1.thrift
Introduce the Embed Reach struct which can be used to describe embed element reach / visibility on different platforms.
Introduce the PlatformTypes enum as a way to describe platforms; this is currently a subset of those used in Ohpan.
> Platform types and embed reach model items

- models/src/main/thrift/content/v1.thrift
- models/src/main/thrift/events/crier/event.thrift
- version.sbt
Ophan require visibility of the date at which an alias ceased to reflect the canonical path for the content. This PR restructures the thrift model by removing the previous `string` representation and applies a new `AliasPath` type.
Ensure that aliasPaths are properly represented in Concierge responses, capi scala client models, crier events, pubflow monitoring events and fastly decache events.
The correct data appears in the correct places in the correct format? Success!
We're now changing more of the existing model but the feature isn't widely adopted yet, and because use of these are opt-in we don't imaging seeing any unexpected failures.
N/A
> Add the ceasedToBeCanonicalAt datetime to evolved URL aliasPaths

- models/src/main/thrift/content/v1.thrift
See [#36](https://github.com/guardian/flexible-model/pull/36), [#2586](https://github.com/guardian/content-api/pull/2586) and [#2596](https://github.com/guardian/content-api/pull/2596).
Adds the 'code element type' to the capi model, along with html and language type fields.
This is ultimately to allow blocks of code to work in our developer blogs (previously these have been handled by html injection rather than content modelling).
I think we need to deploy a full pipeline from flex to concierge, including the models, and test the behaviour. But I need a second opinion on this.
> Add code element type fields

- README.md
- build.sbt
- version.sbt
Snyk was starting to grumble about our thrift version, so we've updated it to `0.13.0` (this is the most compatible with our other dependencies at the moment).
The plan would probably be to incorporate these models into e.g. [content-api-scala-client](https://github.com/guardian/content-api-scala-client) and run some tests with that. 
Nothing falls apart or has tantrums? Success!
It might not work as expected, in which case we wouldn't release it as-is. We ought to be able to have locally built test releases that we can use to figure that out before it becomes a problem though.
> Update thrift to 0.13.0

- project/plugins.sbt
- version.sbt
Our sbt-scrooge-typescript sbt plugin is now published to Maven, so we should get it from there.
I ran a release using the RC3 build of sbt-scrooge-typescript and subsequently released content-api-models 16.1.0-RC1 to Maven and the corresponding @guardian/content-api-models@16.1.0-RC1 to NPM (which I think is the step that relies on the plugin)
The RC build reached NPM and looks complete (AFAICT) - https://www.npmjs.com/package/@guardian/content-api-models/v/16.1.0-RC1
Consumers may experience problems if there's anything wrong with the models, but updates can be made quite rapidly if there are any issues.
N/A
N/A
> Consume sbt-scrooge-typescript 1.3.0 from Maven

- README.md
- project/plugins.sbt
- version.sbt
There's a newer version of the sbt-scrooge-typescript sbt plugin available (as a result of https://github.com/guardian/scrooge-extras/pull/18) which removes the last dependency on thrift `0.12.0`. We hope.
This change should be invisible unless the updates in the plugin have unexpected side effects. I'll aim to release this as a release candidate build and test with the CAPI scala client. Apps Rendering may have to do the same to explore whether they have issues with Int64 conversions.
If nobody finds anything wrong with the release candidate build we can proceed with a full release.
It's possible that clients may run into Int64 parsing problems but we ought to have enough test coverage to discover that quite quickly.
N/A
N/A
> Import updated sbt-scrooge-typescript plugin 1.4.0

- README.md
Added further clarification on the release process to README.md to make it clearer that releases should be made from main not from branches.
> Updating readMe to make release process clearer

- models/src/main/thrift/events/fastly/event.thrift
Allows consumers to make informed decisions about older messages.
ie. This happened a week ago; I don't need to be retry it so aggressively or I can drop it.
- Optional for backwards compatiblity
- Choose not to use the fill CapiDateTime; these events aren't really about CAPI; it's what the crier package does; avoids cross package linkage.
- published field name could have been dateTime (crier) or firstPublished etc. published seems the simplest descriptive verb.
> Mark content decached events with a published timestamp

- build.sbt
- project/build.properties
*Bump `sbt` to `1.5.7`
*Swap out deprecated `in` syntax in `build.sbt` and other deprecated syntax
Compiled and successfully published locally.
TBA
Low-risk change.
> Updating sbt to 1.5.7

- .gitignore
- README.md
- build.sbt
- models/src/main/thrift/content/v1.thrift
- project/plugins.sbt
- version.sbt
Upgrade our dependencies and plugins to their latest available versions. This build brings in beta releases of some upstream libraries for testing while they have their own PRs open.
This branch was used to release the following builds;
[content-api-models-json 17.3.0-beta.2 for scala 2.12](https://repo1.maven.org/maven2/com/gu/content-api-models-json_2.12/17.3.0-beta.2/)
[content-api-models-json 17.3.0-beta.2 for scala 2.13](https://repo1.maven.org/maven2/com/gu/content-api-models-json_2.13/17.3.0-beta.2/)
[content-api-models 17.3.0-beta.2](https://repo1.maven.org/maven2/com/gu/content-api-models/17.3.0-beta.2/)
and
[@guardian/content-api-models 17.3.0-beta.2 for typescript](https://www.npmjs.com/package/@guardian/content-api-models/v/17.3.0-beta.2)
(note that the maven links above may …
> Upgrade dependencies

- .github/workflows/snyk.yml
Updates this repository's Snyk integration to use the correct branch name in the workflow trigger.
> fix: use correct default branch name for Snyk workflow

- models/src/main/thrift/content/v1.thrift
- version.sbt
This PR forms part of the process of adding the `showTableOfContents` Property to CAPI. In order to facilitate this and for it be consumed ultimately by the CAPI- Porter service, we need to publish a model.
We have published a SNAPSHOT version to `Sonatype` - version: `17.4.1-SNAPSHOT` and tested this version in Concierge locally.
1. content-api/elasticsearch: Add Table of Contents type to elasticsearch https://github.com/guardian/content-api/pull/2718
2. content-api/porter: Add Table of Contents field to porter https://github.com/guardian/content-api/pull/2719
3. content-api-models: Add Table of Contents to capi thrift model **(current PR)**
4. content-api/concierge: update content-api-models version to add Table of Contents in concierge - …
> add tableofcontents to capi thrift model

- build.sbt
This bumps `content-atom` to 3.4.1. This version includes an optional youtube override image, only to be used in `media-atom-maker`.
> Bump content-atom version to 3.4.1

- models/src/main/thrift/content/v1.thrift
- version.sbt
Adds `optional bool isMandatory` fields to
* AudioElementFields
* CommentElementFields
* ContentAtomElementFields
* TweetElementFields
* VideoElementFields
This is to make us consistent with https://github.com/guardian/flexible-model/pull/54
Output a [beta build](https://repo1.maven.org/maven2/com/gu/content-api-models-scala_2.13/17.5.0-beta.0/), consume and test in other applications.
I've imported the above beta build into Concierge and successfully ran all tests locally.
If consuming applications don't fall apart with this version - success!
This is new data, so it shouldn't have unpleasant side effects for existing consumers.
N/A
-   [ ] [Navigable …
> Shadow isMandatory changes from flexible-model

- models/src/main/thrift/content/v1.thrift
- version.sbt
Add the initial structures to support content channels. These will likely grow over time but for now, this is the minimum we need to get started.
We'll build and release a local SNAPSHOT for local testing, then potentially make a beta release version for CODE testing before a final release for PROD.
Update:
Most recently released as `17.6.0-beta.1` to maven and npm. Have tested with that build.
These effects will become visible in CAPI output at various points during testing.
Risk is very low. We're adding data so any consumers of prior versions will be none the wiser anyway.
N/A
> Add initial channel structures

- models/src/main/thrift/content/v1.thrift
- version.sbt
This PR updates the capi model to add the following optional overrides to the callout element type.
- overridePrompt
- overrideTitle
- overrideDescription
This PR is the fifth step of the work for updating the callout element in CAPI pipeline:
1. flexible-model: https://github.com/guardian/flexible-model/pull/55
2. flexible-content: https://github.com/guardian/flexible-content/pull/4233
3. content-api/elasticsearch: https://github.com/guardian/content-api/pull/2754
4. content-api/porter: https://github.com/guardian/content-api/pull/2755
5. **content-api-models**
6. content-api/concierge: https://github.com/guardian/content-api/pull/2756
7. content-api-scala-client: https://github.com/guardian/content-api-scala-client/pull/383
> Add optional callout override fields

- models/src/main/thrift/content/v1.thrift
When we added extra `isMandatory` fields to [catch up with flexible-model](https://github.com/guardian/content-api-models/pull/218), I neglected to also add it to the generic `AssetFields` definition.
Without this in place, when block elements are pulled up to top-level elements in response to the `show-elements=` parameter being used, the top-level `elements` are missing the `isMandatory` data from their `assets`.
-   [x]  Publish the change locally
-   [x]  Test with local Concierge
-   [ ]  Publish
-   [ ]  Repeat test on CODE
Whenever block-level elements that contain `isMandatory` values in their associated `<elementType>TypeData` definition are promoted to top-level elements by `show-elements=`, the `isMandatory` data should be present in those elements.
This is new optional data. …
> Add isMandatory to AssetFields

- json/src/test/resources/templates/item-content-with-blocks.json
- models/src/main/thrift/content/v1.thrift
- version.sbt
This adds the cartoon element to the CAPI model. Follows on from:
https://github.com/guardian/flexible-model/pull/58
https://github.com/guardian/content-api/pull/2769
https://github.com/guardian/content-api/pull/2770
The tests have been updated in `content-api-models-json`. To run:
```
sbt
[>](sbt:root>) ++2.12.11
[>](sbt:root>) test
```
> Add cartoon to content model

- models/src/main/thrift/content/v1.thrift
Adds a new field for sponsorship package.  More information in https://github.com/guardian/tagmanager/pull/508
Virtually identical change to tags-thrift-schema - https://github.com/guardian/tags-thrift-schema/pull/43
> Add optional sponsorship package field

- json/src/main/scala/com/gu/contentapi/json/CirceDecoders.scala
- json/src/main/scala/com/gu/contentapi/json/CirceEncoders.scala
- models/src/main/thrift/content/v1.thrift
Adds a new element type `List` which will be used to provide more structure around existing formats such as Key Takeaways.
This block element is novel in that it also contains block element, creating a recursive data structure. It is not currently anticipated that a `List` element will contain `List` elements, although there is no easy way to prevent this in the thrift definition.
The recursion did cause problems with Fezziwig's auto serialisation, which we have worked around by explicitly caching the serialisers for BlockElement. It is possible that we will change our approach here following work on Fezziwig itself by Emily Bourke.
Run tests, they should pass.
publishLocal and try building/testing content-api-scala-client and content-api with this library.
> Add list element

- models/src/main/thrift/content/v1.thrift
Adds the upcoming Quick-Cryptic crossword type to the CAPI models. Required to have the crossword type correctly parsed from ES and returned in the Concierge response.
Tested as a local snapshot and confirmed working end-to-end through local Crosswordv2/Composer/CAPI
Before:
```
...
"crossword": {
"type": "enum-unknown-crossword-type-1",
...
```
After:
```
...
"crossword": {
"type": "quick-cryptic",
...
```
> Add quick-cryptic crossword type

- models/src/main/thrift/content/schema_org.thrift
Fixing a silly mistake with the thrift. Although it's usually a no-no to change the shape of thrift fields in this case we should be in the clear given it's not being used anywhere yet
-   [ ] [The change doesn't use only colour to convey meaning](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#use-of-colour)
> Tweak a couple of recipe fields to be arrays of strings instead of strings

- build.sbt
This PR https://github.com/guardian/content-api-models/pull/38#discussion_r69474445 set the json's dependency required as "provided" but we are not entirely clearly sure why thta was needed.
ref: https://www.baeldung.com/maven-dependency-scopes#bd-2-provided
It caused problem now because we are not able to see sbt checking on incompatible version, thanks to work done in gha-scala-release where we expect incompatible version fatal errors - https://github.com/guardian/gha-scala-library-release-workflow/blob/add-configuration-guidence/docs/configuration.md#recommended-sbt-plugins
co-authored with @rtyley along with @emdash-ie 
Try change version for capi-model-scala-client to older version so that while running test/compile sbt should point out the issues in incomptaible versions. …
> Ensure sbt detects version incompatibilities

- models/src/main/thrift/content/v1.thrift
-   [ ] [The change doesn't use only colour to convey meaning](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#use-of-colour)
> Timeline model

- build.sbt
We are testing latest `content-entity` release after implementing gha-scala-release-process in it.
Since we bumped its version to content-atom and released its preview release hence umping that too to avoid semver version conflicts.
https://github.com/guardian/content-atom/pull/169
Make preview release for this and will test in `content-api-scala-client`
> Bump version of content-entity and content-atom preview

- build.sbt
- json/src/main/scala/com/gu/contentapi/json/CirceDecoders.scala
- json/src/main/scala/com/gu/contentapi/json/CirceEncoders.scala
- json/src/test/scala-2.12/com/gu/contentapi/json/CirceRoundTripSpec.scala
This PR updates the version of fezziwig to 2.0.0, which includes the changes from [fezziwig PR#48](https://github.com/guardian/fezziwig/pull/48), and updates the CirceEncoders and CirceDecoders as required.
Unfortunately this requires a lot of boilerplate semiauto derivation! But fortunately, it’s a little less mysterious: we no longer need fully manual encoders for Map-containing types, for example. Compile times are also somewhat improved, as described in that PR.
> Update fezziwig to v2.0.0

- models/src/main/thrift/content/v1.thrift
Expands the list model to include fields required by Mini profiles and Multi-byline formats. This brings the model into line with flexible-model: https://github.com/guardian/flexible-model/pull/69
-   [ ] [The change doesn't use only colour to convey meaning](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#use-of-colour)
> Expand list model to include fields required by Mini profiles and Multi-byline formats

- .github/workflows/ci.yml
- .github/workflows/release.yml
Adds `setup-sbt` to workflow
Note that `setup-scala` was not used due to a discrepancy between the `java-version` in `setup-java` and that in the pre-existing `.tool-versions` file
Workflow ran successfully on this branch
No more failing workflows
-   [ ] [The change doesn't use only colour to convey meaning](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#u …
> Add setup-sbt to workflow

- models/src/main/thrift/content/v1.thrift
Previously, we assumed multi-byline contributors would be modelled as tag objects in CAPI (https://github.com/guardian/content-api-models/pull/247).
However, for rendering purposes, it's actually sufficient to model them as IDs (e.g. `["profile/owen-jones"]`). When we render the multi-byline element, these IDs will be mapped to the contributor tags on the article level, which contain all the relevant metadata (image URL, etc.)
Example CAPI response (simplified):
```
{
"blocks": {
"body": [
{
"elements": [
{
"type": "list",
"listTypeData": {
"type": "multi-byline"
"items": [
{
"title": "Labour is the only party serious about building homes",
"bio": "David Miliband is CEO of the International Rescue Committee",
"elements": [ ... ],
"contributorIds": ["profile/davidmiliband"],
"bylineHtml": …
```
> Model multi-byline contributor as strings instead of Tags

- models/src/main/thrift/content/v1.thrift
Adds new field for deeply read articles. See https://github.com/guardian/content-api/pull/2971
> Add field for deeply-read

- models/src/main/thrift/content/v1.thrift
Adds the upcoming Sunday quick crossword type (distinct from Quick!) to the CAPI models. Required to have the crossword type correctly parsed from ES and returned in the Concierge response.
> add sunday-quick crossword type

- json/src/main/scala/com/gu/contentapi/json/CirceDecoders.scala
- json/src/main/scala/com/gu/contentapi/json/CirceEncoders.scala
- models/src/main/thrift/content/v1.thrift
Co-authored-by: Emma Imber <emma-jo.imber@guardian.co.uk>
Added link to the API model
The reason behind this change can be found [here](https://docs.google.com/document/d/1mG5z_RifG73DAzNGo7Jeq3IADDlLLM5YeywvbwsTD6I/edit?tab=t.0#heading=h.8rus61czp6e9) 
-   [ ] [The change doesn't use only colour to convey meaning](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visua …
> Added link to the API model

- models/src/main/thrift/content/v1.thrift
We are in the process of adding two new podcast metadata fields to the tag model: 
- `episodicArtworkEnabled` (boolean)
- `episodicArtworkEnabledFrom` (datetime)
They are already supported in Porter: https://github.com/guardian/content-api/pull/3093
Now we need to add them to the CAPI model
This will be testable when we have a Concierge PR up which consumes this version of the library
- [tags-thrift-schema](https://github.com/guardian/tags-thrift-schema/pull/48)
- [tagmanager](https://github.com/guardian/tagmanager/pull/558)
- [content-api (Porter)](https://github.com/guardian/content-api/pull/3093)
- [content-api-models](https://github.com/guardian/content-api-models/pull/261)  <- you are here
- [content-api (Concierge) ](https://github.com/guardian/content-api/pull/3100) 
- …
> Add episodic artwork fields to CAPI model

- build.sbt
Bumps to include https://github.com/guardian/content-atom/releases/tag/v6.1.0.
> Update content atom model to latest
