- src/main/thrift/content/v1.thrift
> Add some new optional fields to Blocks

- src/main/thrift/content/v1.thrift
This is the response that shows where a given atom is being used.
> Add AtomUsageResponse struct

- build.sbt
- json/src/main/scala/com/gu/contentapi/json/JsonParser.scala
Hopefully the cause of the higher cpu usage on Concierge
> Use jackson instead of native json4s

- build.sbt
- models/src/main/thrift/content/v1.thrift
See [elasticsearch related change](https://github.com/guardian/content-api/pull/1529).
> Add podcast categories

- models/src/main/thrift/events/crier/event.thrift
This is used to handle large update events in Crier
> Add a RetrievableContent payload type.

- build.sbt
- json/src/main/scala/com/gu/contentapi/json/Serialization.scala
- json/src/test/resources/templates/item-content-with-atom-media.json
- json/src/test/resources/templates/item-content-with-atom-quiz.json
- json/src/test/scala/com/gu/contentapi/json/SerializationSpec.scala
- models/src/main/thrift/content/v1.thrift
[content-atom change](https://github.com/guardian/content-atom/commit/21247f54c677d5506e238fa2046917af2822f2c4)
[concierge change](https://github.com/guardian/content-api/pull/1561)
> Add media atom type

- json/src/main/scala/com/gu/contentapi/json/CirceSerialization.scala
- json/src/test/resources/templates/content-with-blocks.json
- json/src/test/scala/com/gu/contentapi/json/CirceSpec.scala
This is to fix the boolean block attributes (keyEvent, summary, pinned)
> Support decoding of Boolean from JSON strings ("true"/"false")

- models/src/main/thrift/content/v1.thrift
- Adds vine to thrift. Definition in porter [here](https://github.com/guardian/content-api/blob/master/porter/src/main/thrift/flexible/content.thrift#L847).
> adds vine to thrift

- json/src/main/scala/com/gu/contentapi/json/CirceSerialization.scala
This is necessary for replacing the json4s processing logic in concierge
> Add some missing circe decoders

- models/src/main/thrift/content/v1.thrift
Add the new isMandatory field and missing role field for Interactive.
> Adding the isMandatory Field

- macros/src/main/scala/com/gu/contentapi/circe/CirceScroogeMacros.scala
This is a partial workaround for travisbrown/circe#329. Instead of calling `.get` directly on the `HCursor`, we perform the down-fielding on its underlying `Cursor`. This means that history is not preserved, resulting in fewer object allocations and less GC pressure.
The only downside to this is that we can't include the cursor history in error messages, but we don't really care about that.
> Circe macro: discard history when decoding

- build.sbt
- json/src/main/scala/com/gu/contentapi/json/CirceSerialization.scala
- models/src/main/thrift/content/v1.thrift
+ Bump the content-atom library
+ add support for CTA to the API model
+ add support for CTA to serialization code
> Add support for CTA atom

- build.sbt
- json/src/main/scala/com/gu/contentapi/json/CirceDecoders.scala
- json/src/main/scala/com/gu/contentapi/json/CirceEncoders.scala
- models/src/main/thrift/content/v1.thrift
Add interactive atom to models
> Add interactive atom

- build.sbt
> Bump content-atom to 2.4.13

- build.sbt
https://github.com/guardian/content-atom/pull/66
> Bump content-atom to 2.4.20 for film review atom support

- macros/src/main/scala/com/gu/contentapi/circe/CirceScroogeMacros.scala
Refactors the existing Thrift encoder/decoder macros to use a [macro bundle](http://docs.scala-lang.org/overviews/macros/bundles).
The main advantage here is that it allows multiple macro implementations to share common logic, because in the bundle all the methods now share the same context and universe. See the private methods at the end of `CirceScroogeMacrosImpl` for this shared logic.
I think this makes the code a *lot* more readable (by the standards of scala macros).
With thanks to @philwills for the [original suggestion](https://github.com/guardian/content-api-models/pull/81#discussion_r91917708)
> Use macro bundle

- benchmarks/src/main/scala/benchmark/JsonDecodeBenchmark.scala
- build.sbt
- json/src/main/scala/com/gu/contentapi/json/CirceDecoders.scala
- json/src/test/scala/com/gu/contentapi/json/CirceRoundTripSpec.scala
- json/src/test/scala/com/gu/contentapi/json/utils/JsonHelpers.scala
> Circe 0.7.0

- build.sbt
- Renames questions field to storyquestions.
> Bump content-atom dependency to 2.4.34.

- build.sbt
https://github.com/guardian/content-entity/pull/7
> Bump content-entity-thrift to 0.1.5

- json/src/test/resources/templates/item-content-with-blocks.json
- models/src/main/thrift/content/v1.thrift
See [flexbile change](https://github.com/guardian/flexible-content/pull/2807)
> Add membership placeholder

- models/src/main/thrift/content/v1.thrift
This is as part of a wider piece of work to get weekend crosswords being published interactively
> Add weekend crossword type.

- json/src/test/resources/templates/entities.json
- json/src/test/scala/com/gu/contentapi/json/CirceRoundTripSpec.scala
- models/src/main/thrift/content/v1.thrift
In preparation for the `/entities` endpoint
> Add EntitiesResponse

- json/src/main/scala/com/gu/contentapi/json/CirceDecoders.scala
- json/src/main/scala/com/gu/contentapi/json/CirceEncoders.scala
> Encoder/Decoder for Entity

- models/src/main/thrift/content/v1.thrift
> Add story to ItemResponse

- models/src/main/thrift/content/v1.thrift
This is currently inconsistent across projects
> qa -> qanda

- build.sbt
For storyquestions `closeDate` field
> content-atom 2.4.44

- models/src/main/thrift/content/v1.thrift
Related:
https://github.com/guardian/content-api/pull/2030
> Add Sponsorship field to Rich Links

- build.sbt
> content-atom 2.4.53

- build.sbt
> content-atom 2.4.57

- build.sbt
Update content atom model version
> content-atom 2.4.59

- build.sbt
> content-atom 2.4.60

- build.sbt
- models/src/main/thrift/content/v1.thrift
Part of the work this quarter to make charts built by interactives into atoms
> Add chart atom to content api model and bump atom library.

- .travis.yml
- build.sbt
- models/src/main/thrift/content/v1.thrift
When [the `content-atom` update](https://github.com/guardian/content-atom/pull/125) has been released.
> Add hook for audio atoms

- build.sbt
Removes the tools-related data in the `MediaAtom`
> Bump atom model

- build.sbt
bump content-atom version to latest
> bump content-atom version

- .sbtopts
> add .sbtopts

- models/src/main/thrift/content/v1.thrift
adds byline and pullquote
https://github.com/guardian/flexible-content/pull/3340
> byline and pullquote role

- models/src/main/thrift/content/v1.thrift
Will be exposed to internal users only
> Add `Tag#internalName`

- build.sbt
- json/src/test/scala/com/gu/contentapi/json/CirceRoundTripSpec.scala
- project/plugins.sbt
> Build against scala 2.13

- build.sbt
- json/src/main/scala/com/gu/contentapi/json/CirceDecoders.scala
- json/src/main/scala/com/gu/contentapi/json/CirceEncoders.scala
- models/src/main/thrift/content/v1.thrift
- project/plugins.sbt
The Ophan routes have been removed so this can go away too.
> Deprecate storyquestions

- build.sbt
We need to increment this to add a new type of chart atom
> Version bump:  content-atom

- build.sbt
Adding in all chart types needed for this quarter.
> Version Bump: bump content atom again to 3.12

- models/src/main/thrift/content/v1.thrift
> Add missing emailsignup field

- models/src/main/thrift/events/crier/event.thrift
To help consumers decide if they are interested in this update before incurring the cost of fetching it.
> The RetrievableContent event adds a content type convenience field

- project/plugins.sbt
- version.sbt
Latest sonatype plug in.
Specifically the 3.9 series includes:
```
Add sonatypeTimeoutMillis to wait longer time until close/promote stage completes. The default is 60 minutes.
```
> Update sbt sonatype plugin to latest

- README.md
Remind backend developers what `tsc` stands for.
> Document what tsc is

- build.sbt
Bumping content atom to 4.0.0 to deprecate recipe atom
> Bump content atom version

- json/src/test/scala-2.12/com/gu/contentapi/json/CirceRoundTripSpec.scala
Add test to show correct serialisation of us-exclusive sponsorship package
Mainly to reassure me, but since I've written it, I thought I might as well open a PR.
> Sponsorship Package test

- models/src/main/thrift/content/v1.thrift
Adds the upcoming Special crossword type to the CAPI models. Required to have the crossword type correctly parsed from ES and returned in the Concierge response.
> Add special crossword type
